server:
  port: 8083
  error:
    include-message: always

spring:
  datasource:
    driverClassName:
    url: jdbc:mysql://localhost:3306/segbaya
#    url: jdbc:mysql://localhost:3306/segbaya
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 2000KB
      max-request-size: 2000KB

